version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=tamupos
      - POSTGRES_PASSWORD=tamupos
      - POSTGRES_DB=tamupos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data: 