# Render Blueprint
# See https://render.com/docs/blueprint-spec for more details

databases:
  - name: tamu_pos_db
    databaseName: tamu_pos
    user: tamu_user
    plan: free # Or your desired plan
    region: oregon # Or your desired region

services:
  # ==================================
  #         Backend API
  # ==================================
  - type: web
    name: tamupos-backend
    runtime: node
    region: oregon
    plan: free # Or your desired plan
    branch: main # Or your production branch
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tamu_pos_db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true # Let Render generate a secure secret
      - key: MPESA_CALLBACK_URL
        value: "https://tamupos-backend.onrender.com/api/payments/callback" # Update with your actual Render URL
      - key: MPESA_BASE_URL
        value: "https://sandbox.safaricom.co.ke" # Change to production URL when ready
    buildCommand: |
      cd backend
      npm install
      npx prisma generate
      npm run build
    startCommand: |
      cd backend
      npm start

  # ==================================
  #       Frontend Static Site
  # ==================================
  - type: web
    name: tamupos-frontend
    runtime: static
    region: oregon
    plan: free # Or your desired plan
    branch: main
    staticPublishPath: ./frontend/dist
    buildCommand: |
      cd frontend
      npm install
      npm run build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://tamupos-backend.onrender.com/api/* # Proxy API requests
      - type: rewrite
        source: /*
        destination: /index.html 